
import './bootstrap';

import Alpine from 'alpinejs';
import { exportDataTablePDF, exportContentPDF } from './pdf-export.js';
import { initSidebar, toggleSidebar, closeSidebar } from './sidebar';
import { initDropdown } from './dropdown.js';
import { DataTableManager } from './datatables-init.js';
import { initModals } from './modals.js';
import { ExcelExporter } from './excel-export';
import { initLoadingSpinner } from './loading-spinner';
import { createStatusFilter } from './status-filter.js';
import { initDatatableFilter } from './datatables-filters.js';
import { updateInputBackground, initInputBackgrounds } from './input-background.js';
import { initPasswordToggle } from './password-toggle.js';
import * as KaryawanRowManager from './karyawan-row-manager.js';
import { initWebcam } from './webcam.js';
import { clearOldImageStorages } from './image-storage';
import { initSupabaseRealtime } from './supabase-realtime.js';
import * as Recaptcha from './captcha';
import { setupFormValidation, validateNama, validateEmail } from './form-validation';
import { createAutocomplete } from './autocomplete';

window.toggleSidebar = toggleSidebar;
window.closeSidebar = closeSidebar;
window.exportDataTablePDF = exportDataTablePDF;
window.exportContentPDF = exportContentPDF;
window.DataTableManager = DataTableManager;
window.ExcelExporter = ExcelExporter;
window.createStatusFilter = createStatusFilter;
window.updateInputBackground = updateInputBackground;
window.addKaryawanRow = KaryawanRowManager.addKaryawanRow;
window.removeKaryawanRow = KaryawanRowManager.removeKaryawanRow;
window.setupRowListeners = KaryawanRowManager.setupRowListeners;
window.searchKaryawan = KaryawanRowManager.searchKaryawan;
window.displayAutocomplete = KaryawanRowManager.displayAutocomplete;
window.selectKaryawan = KaryawanRowManager.selectKaryawan;
window.renderKaryawanCard = KaryawanRowManager.renderKaryawanCard;
window.updateHiddenInput = KaryawanRowManager.updateHiddenInput;
window.resetKaryawanRow = KaryawanRowManager.resetKaryawanRow;
window.updateMinusButtonsVisibility = KaryawanRowManager.updateMinusButtonsVisibility;
window.setSearchKaryawanRoute = KaryawanRowManager.setSearchKaryawanRoute;
window.setEscapeHtmlFn = KaryawanRowManager.setEscapeHtmlFn;
window.getSelectedKaryawan = KaryawanRowManager.getSelectedKaryawan;
window.Recaptcha = Recaptcha;
window.setupFormValidation = setupFormValidation;
window.validateNama = validateNama;
window.validateEmail = validateEmail;
window.createAutocomplete = createAutocomplete;

document.addEventListener('DOMContentLoaded', function() {
    clearOldImageStorages();
    initDropdown('dropdown');
    initSidebar();
    initLoadingSpinner();
    initModals();
    initInputBackgrounds();
    initPasswordToggle();
    initWebcam();
    initSupabaseRealtime();
    initDatatableFilter();
    Alpine.start();
});